<a href="https://colab.research.google.com/github/pavannaik321/master_computer_vision/blob/main/TensorFlow_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [6]:
tensor_one_d = tf.constant([2,0,-3,8,90])
print(tensor_one_d)

tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int32)


In [8]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [9]:
tensor_three_d = tf.constant([
    [
        [1,5,6],
         [2,3,8]
    ],
    [
        [2,3,4],
        [5,6,8]
    ],
    [
        [7,6,7],
        [5,4,3]
    ]
])
print(tensor_three_d)

tf.Tensor(
[[[1 5 6]
  [2 3 8]]

 [[2 3 4]
  [5 6 8]]

 [[7 6 7]
  [5 4 3]]], shape=(3, 2, 3), dtype=int32)


In [11]:
print(tensor_three_d.shape)
print(tensor_one_d.shape)
print(tensor_two_d.shape)

(3, 2, 3)
(5,)
(4, 3)


In [12]:
print(tensor_three_d.ndim)
print(tensor_one_d.ndim)
print(tensor_two_d.ndim)

3
1
2


In [13]:
# Convert numpy array to tensor
import numpy as np
np_array = np.array([1,2,3,4])
print(np_array)

[1 2 3 4]


In [14]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


In [15]:
# Create identity matrix
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
